# backend/Dockerfile
# Use official Node.js LTS image
FROM node:16-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm ci --only=production

# Bundle app source
COPY . .

# Expose port and start application
EXPOSE 4000
CMD ["node", "index.js"]